# Generated by Django 3.2.6 on 2021-08-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210830_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
